const logger = require('./src/config/logger');
const { Location } = require('./src/models');

const counties = [
  {
    code: 'AB',
    name: 'Alba',
    aliases: ['ALBA'],
    cities: [
      { name: 'Alba Iulia', code: 'AB1', type: 'municipality', aliases: ['ALBA IULIA', 'Mun. Alba Iulia'] },
      { name: 'Aiud', code: 'AB2', type: 'municipality', aliases: ['AIUD', 'Mun. Aiud'] },
      { name: 'Blaj', code: 'AB3', type: 'municipality', aliases: ['BLAJ', 'Mun. Blaj'] },
      { name: 'Sebeș', code: 'AB4', type: 'municipality', aliases: ['SEBES', 'SEBEŞ', 'Mun. Sebeș'] },
      { name: 'Abrud', code: 'AB5', type: 'city', aliases: ['ABRUD'] },
      { name: 'Baia de Arieș', code: 'AB6', type: 'city', aliases: ['BAIA DE ARIES', 'BAIA DE ARIEŞ'] },
      { name: 'Câmpeni', code: 'AB7', type: 'city', aliases: ['CAMPENI', 'CÂMPENI'] },
      { name: 'Cugir', code: 'AB8', type: 'city', aliases: ['CUGIR'] },
      { name: 'Ocna Mureș', code: 'AB9', type: 'city', aliases: ['OCNA MURES', 'OCNA MUREŞ'] },
      { name: 'Teiuș', code: 'AB10', type: 'city', aliases: ['TEIUS', 'TEIUŞ'] },
      { name: 'Zlatna', code: 'AB11', type: 'city', aliases: ['ZLATNA'] },
    ],
  },
  {
    code: 'AR',
    name: 'Arad',
    aliases: ['ARAD'],
    cities: [
      { name: 'Arad', code: 'AR1', type: 'municipality', aliases: ['ARAD', 'Mun. Arad'] },
      { name: 'Chișineu-Criș', code: 'AR2', type: 'city', aliases: ['CHISINEU-CRIS', 'CHIŞINEU-CRIŞ'] },
      { name: 'Curtici', code: 'AR3', type: 'city', aliases: ['CURTICI'] },
      { name: 'Ineu', code: 'AR4', type: 'city', aliases: ['INEU'] },
      { name: 'Lipova', code: 'AR5', type: 'city', aliases: ['LIPOVA'] },
      { name: 'Nădlac', code: 'AR6', type: 'city', aliases: ['NADLAC', 'NĂDLAC'] },
      { name: 'Pâncota', code: 'AR7', type: 'city', aliases: ['PANCOTA', 'PÂNCOTA'] },
      { name: 'Pecica', code: 'AR8', type: 'city', aliases: ['PECICA'] },
      { name: 'Sântana', code: 'AR9', type: 'city', aliases: ['SANTANA', 'SÂNTANA'] },
      { name: 'Sebiș', code: 'AR10', type: 'city', aliases: ['SEBIS', 'SEBIŞ'] },
    ],
  },
  {
    code: 'AG',
    name: 'Argeș',
    aliases: ['ARGES', 'ARGEŞ'],
    cities: [
      { name: 'Pitești', code: 'AG1', type: 'municipality', aliases: ['PITESTI', 'PITEŞTI', 'Mun. Pitești'] },
      { name: 'Câmpulung', code: 'AG2', type: 'municipality', aliases: ['CAMPULUNG', 'CÂMPULUNG'] },
      { name: 'Curtea de Argeș', code: 'AG3', type: 'municipality', aliases: ['CURTEA DE ARGES', 'CURTEA DE ARGEŞ'] },
      { name: 'Mioveni', code: 'AG4', type: 'city', aliases: ['MIOVENI'] },
      { name: 'Costești', code: 'AG5', type: 'city', aliases: ['COSTESTI', 'COSTEŞTI'] },
      { name: 'Ștefănești', code: 'AG6', type: 'city', aliases: ['STEFANESTI', 'ŞTEFĂNEŞTI'] },
      { name: 'Topoloveni', code: 'AG7', type: 'city', aliases: ['TOPOLOVENI'] },
    ],
  },
  {
    code: 'BC',
    name: 'Bacău',
    aliases: ['BACAU', 'BACĂU'],
    cities: [
      { name: 'Bacău', code: 'BC1', type: 'municipality', aliases: ['BACAU', 'BACĂU', 'Mun. Bacău'] },
      { name: 'Onești', code: 'BC2', type: 'municipality', aliases: ['ONESTI', 'ONEŞTI'] },
      { name: 'Moinești', code: 'BC3', type: 'municipality', aliases: ['MOINESTI', 'MOINEŞTI'] },
      { name: 'Comănești', code: 'BC4', type: 'city', aliases: ['COMANESTI', 'COMĂNEŞTI'] },
      { name: 'Buhuși', code: 'BC5', type: 'city', aliases: ['BUHUSI', 'BUHUŞI'] },
      { name: 'Dărmănești', code: 'BC6', type: 'city', aliases: ['DARMANESTI', 'DĂRMĂNEŞTI'] },
      { name: 'Slănic-Moldova', code: 'BC7', type: 'city', aliases: ['SLANIC-MOLDOVA', 'SLĂNIC-MOLDOVA'] },
      { name: 'Târgu Ocna', code: 'BC8', type: 'city', aliases: ['TARGU OCNA', 'TÂRGU OCNA'] },
    ],
  },
  {
    code: 'BH',
    name: 'Bihor',
    aliases: ['BIHOR'],
    cities: [
      { name: 'Oradea', code: 'BH1', type: 'municipality', aliases: ['ORADEA', 'Mun. Oradea'] },
      { name: 'Salonta', code: 'BH2', type: 'municipality', aliases: ['SALONTA'] },
      { name: 'Marghita', code: 'BH3', type: 'municipality', aliases: ['MARGHITA'] },
      { name: 'Beiuș', code: 'BH4', type: 'municipality', aliases: ['BEIUS', 'BEIUŞ'] },
      { name: 'Aleșd', code: 'BH5', type: 'city', aliases: ['ALESD', 'ALEŞD'] },
      { name: 'Nucet', code: 'BH6', type: 'city', aliases: ['NUCET'] },
      { name: 'Săcueni', code: 'BH7', type: 'city', aliases: ['SACUENI', 'SĂCUENI'] },
      { name: 'Ștei', code: 'BH8', type: 'city', aliases: ['STEI', 'ŞTEI'] },
      { name: 'Valea lui Mihai', code: 'BH9', type: 'city', aliases: ['VALEA LUI MIHAI'] },
      { name: 'Vașcău', code: 'BH10', type: 'city', aliases: ['VASCAU', 'VAŞCĂU'] },
    ],
  },
  {
    code: 'BN',
    name: 'Bistrița-Năsăud',
    aliases: ['BISTRITA-NASAUD', 'BISTRIŢA-NĂSĂUD'],
    cities: [
      { name: 'Bistrița', code: 'BN1', type: 'municipality', aliases: ['BISTRITA', 'BISTRIŢA', 'Mun. Bistrița'] },
      { name: 'Beclean', code: 'BN2', type: 'city', aliases: ['BECLEAN'] },
      { name: 'Năsăud', code: 'BN3', type: 'city', aliases: ['NASAUD', 'NĂSĂUD'] },
      { name: 'Sângeorz-Băi', code: 'BN4', type: 'city', aliases: ['SANGEORZ-BAI', 'SÂNGEORZ-BĂI'] },
    ],
  },
  {
    code: 'BT',
    name: 'Botoșani',
    aliases: ['BOTOSANI', 'BOTOŞANI'],
    cities: [
      { name: 'Botoșani', code: 'BT1', type: 'municipality', aliases: ['BOTOSANI', 'BOTOŞANI', 'Mun. Botoșani'] },
      { name: 'Dorohoi', code: 'BT2', type: 'municipality', aliases: ['DOROHOI'] },
      { name: 'Darabani', code: 'BT3', type: 'city', aliases: ['DARABANI'] },
      { name: 'Flămânzi', code: 'BT4', type: 'city', aliases: ['FLAMANZI', 'FLĂMÂNZI'] },
      { name: 'Săveni', code: 'BT5', type: 'city', aliases: ['SAVENI', 'SĂVENI'] },
      { name: 'Ștefănești', code: 'BT6', type: 'city', aliases: ['STEFANESTI', 'ŞTEFĂNEŞTI'] },
      { name: 'Bucecea', code: 'BT7', type: 'city', aliases: ['BUCECEA'] },
    ],
  },
  {
    code: 'BV',
    name: 'Brașov',
    aliases: ['BRASOV', 'BRAŞOV'],
    cities: [
      { name: 'Brașov', code: 'BV1', type: 'municipality', aliases: ['BRASOV', 'BRAŞOV', 'Mun. Brașov'] },
      { name: 'Făgăraș', code: 'BV2', type: 'municipality', aliases: ['FAGARAS', 'FĂGĂRAŞ'] },
      { name: 'Săcele', code: 'BV3', type: 'municipality', aliases: ['SACELE', 'SĂCELE'] },
      { name: 'Codlea', code: 'BV4', type: 'municipality', aliases: ['CODLEA'] },
      { name: 'Râșnov', code: 'BV5', type: 'city', aliases: ['RASNOV', 'RÂŞNOV'] },
      { name: 'Zărnești', code: 'BV6', type: 'city', aliases: ['ZARNESTI', 'ZĂRNEŞTI'] },
      { name: 'Victoria', code: 'BV7', type: 'city', aliases: ['VICTORIA'] },
      { name: 'Predeal', code: 'BV8', type: 'city', aliases: ['PREDEAL'] },
      { name: 'Rupea', code: 'BV9', type: 'city', aliases: ['RUPEA'] },
      { name: 'Ghimbav', code: 'BV10', type: 'city', aliases: ['GHIMBAV'] },
    ],
  },
  {
    code: 'BR',
    name: 'Brăila',
    aliases: ['BRAILA', 'BRĂILA'],
    cities: [
      { name: 'Brăila', code: 'BR1', type: 'municipality', aliases: ['BRAILA', 'BRĂILA', 'Mun. Brăila'] },
      { name: 'Făurei', code: 'BR2', type: 'city', aliases: ['FAUREI', 'FĂUREI'] },
      { name: 'Ianca', code: 'BR3', type: 'city', aliases: ['IANCA'] },
      { name: 'Însurăței', code: 'BR4', type: 'city', aliases: ['INSURATEI', 'ÎNSURĂŢEI'] },
    ],
  },
  {
    code: 'B',
    name: 'București',
    aliases: ['BUCURESTI', 'BUCUREȘTI'],
    cities: [
      { name: 'Sector 1', code: 'B1', type: 'sector', aliases: ['SECTOR 1', 'Sectorul 1'] },
      { name: 'Sector 2', code: 'B2', type: 'sector', aliases: ['SECTOR 2', 'Sectorul 2'] },
      { name: 'Sector 3', code: 'B3', type: 'sector', aliases: ['SECTOR 3', 'Sectorul 3'] },
      { name: 'Sector 4', code: 'B4', type: 'sector', aliases: ['SECTOR 4', 'Sectorul 4'] },
      { name: 'Sector 5', code: 'B5', type: 'sector', aliases: ['SECTOR 5', 'Sectorul 5'] },
      { name: 'Sector 6', code: 'B6', type: 'sector', aliases: ['SECTOR 6', 'Sectorul 6'] },
    ],
  },
  {
    code: 'BZ',
    name: 'Buzău',
    aliases: ['BUZAU', 'BUZĂU'],
    cities: [
      { name: 'Buzău', code: 'BZ1', type: 'municipality', aliases: ['BUZAU', 'BUZĂU', 'Mun. Buzău'] },
      { name: 'Râmnicu Sărat', code: 'BZ2', type: 'municipality', aliases: ['RAMNICU SARAT', 'RÂMNICU SĂRAT'] },
      { name: 'Nehoiu', code: 'BZ3', type: 'city', aliases: ['NEHOIU'] },
      { name: 'Pogoanele', code: 'BZ4', type: 'city', aliases: ['POGOANELE'] },
      { name: 'Pătârlagele', code: 'BZ5', type: 'city', aliases: ['PATARLAGELE', 'PĂTÂRLAGELE'] },
    ],
  },
  {
    code: 'CL',
    name: 'Călărași',
    aliases: ['CALARASI', 'CĂLĂRAŞI'],
    cities: [
      { name: 'Călărași', code: 'CL1', type: 'municipality', aliases: ['CALARASI', 'CĂLĂRAŞI', 'Mun. Călărași'] },
      { name: 'Oltenița', code: 'CL2', type: 'municipality', aliases: ['OLTENITA', 'OLTENIŢA'] },
      { name: 'Budești', code: 'CL3', type: 'city', aliases: ['BUDESTI', 'BUDEŞTI'] },
      { name: 'Fundulea', code: 'CL4', type: 'city', aliases: ['FUNDULEA'] },
      { name: 'Lehliu Gară', code: 'CL5', type: 'city', aliases: ['LEHLIU GARA', 'LEHLIU GARĂ'] },
    ],
  },
  {
    code: 'CS',
    name: 'Caraș-Severin',
    aliases: ['CARAS-SEVERIN', 'CARAŞ-SEVERIN'],
    cities: [
      { name: 'Reșița', code: 'CS1', type: 'municipality', aliases: ['RESITA', 'REŞIŢA', 'Mun. Reșița'] },
      { name: 'Caransebeș', code: 'CS2', type: 'municipality', aliases: ['CARANSEBES', 'CARANSEBEŞ'] },
      { name: 'Băile Herculane', code: 'CS3', type: 'city', aliases: ['BAILE HERCULANE', 'BĂILE HERCULANE'] },
      { name: 'Bocșa', code: 'CS4', type: 'city', aliases: ['BOCSA', 'BOCŞA'] },
      { name: 'Moldova Nouă', code: 'CS5', type: 'city', aliases: ['MOLDOVA NOUA', 'MOLDOVA NOUĂ'] },
      { name: 'Oravița', code: 'CS6', type: 'city', aliases: ['ORAVITA', 'ORAVIŢA'] },
      { name: 'Otelu Roșu', code: 'CS7', type: 'city', aliases: ['OTELU ROSU', 'OŢELU ROŞU'] },
      { name: 'Anina', code: 'CS8', type: 'city', aliases: ['ANINA'] },
    ],
  },
  {
    code: 'CJ',
    name: 'Cluj',
    aliases: ['CLUJ'],
    cities: [
      {
        name: 'Cluj-Napoca',
        code: 'CJ1',
        type: 'municipality',
        aliases: ['CLUJ-NAPOCA', 'Mun. Cluj-Napoca', 'CLUJ NAPOCA'],
      },
      { name: 'Turda', code: 'CJ2', type: 'municipality', aliases: ['TURDA'] },
      { name: 'Dej', code: 'CJ3', type: 'municipality', aliases: ['DEJ'] },
      { name: 'Câmpia Turzii', code: 'CJ4', type: 'municipality', aliases: ['CAMPIA TURZII', 'CÂMPIA TURZII'] },
      { name: 'Gherla', code: 'CJ5', type: 'municipality', aliases: ['GHERLA'] },
      { name: 'Huedin', code: 'CJ6', type: 'city', aliases: ['HUEDIN'] },
    ],
  },
  {
    code: 'CT',
    name: 'Constanța',
    aliases: ['CONSTANTA', 'CONSTANŢA'],
    cities: [
      { name: 'Constanța', code: 'CT1', type: 'municipality', aliases: ['CONSTANTA', 'CONSTANŢA', 'Mun. Constanța'] },
      { name: 'Mangalia', code: 'CT2', type: 'municipality', aliases: ['MANGALIA'] },
      { name: 'Medgidia', code: 'CT3', type: 'municipality', aliases: ['MEDGIDIA'] },
      { name: 'Cernavodă', code: 'CT4', type: 'city', aliases: ['CERNAVODA', 'CERNAVODĂ'] },
      { name: 'Eforie', code: 'CT5', type: 'city', aliases: ['EFORIE'] },
      { name: 'Hârșova', code: 'CT6', type: 'city', aliases: ['HARSOVA', 'HÂRŞOVA'] },
      { name: 'Năvodari', code: 'CT7', type: 'city', aliases: ['NAVODARI', 'NĂVODARI'] },
      { name: 'Ovidiu', code: 'CT8', type: 'city', aliases: ['OVIDIU'] },
      { name: 'Murfatlar', code: 'CT9', type: 'city', aliases: ['MURFATLAR'] },
      { name: 'Negru Vodă', code: 'CT10', type: 'city', aliases: ['NEGRU VODA', 'NEGRU VODĂ'] },
      { name: 'Techirghiol', code: 'CT11', type: 'city', aliases: ['TECHIRGHIOL'] },
    ],
  },
  {
    code: 'CV',
    name: 'Covasna',
    aliases: ['COVASNA'],
    cities: [
      { name: 'Sfântu Gheorghe', code: 'CV1', type: 'municipality', aliases: ['SFANTU GHEORGHE', 'SFÂNTU GHEORGHE'] },
      { name: 'Târgu Secuiesc', code: 'CV2', type: 'municipality', aliases: ['TARGU SECUIESC', 'TÂRGU SECUIESC'] },
      { name: 'Baraolt', code: 'CV3', type: 'city', aliases: ['BARAOLT'] },
      { name: 'Covasna', code: 'CV4', type: 'city', aliases: ['COVASNA'] },
      { name: 'Întorsura Buzăului', code: 'CV5', type: 'city', aliases: ['INTORSURA BUZAULUI', 'ÎNTORSURA BUZĂULUI'] },
    ],
  },
  {
    code: 'DB',
    name: 'Dâmbovița',
    aliases: ['DAMBOVITA', 'DÂMBOVIŢA'],
    cities: [
      { name: 'Târgoviște', code: 'DB1', type: 'municipality', aliases: ['TARGOVISTE', 'TÂRGOVIŞTE'] },
      { name: 'Moreni', code: 'DB2', type: 'municipality', aliases: ['MORENI'] },
      { name: 'Găești', code: 'DB3', type: 'city', aliases: ['GAESTI', 'GĂEŞTI'] },
      { name: 'Pucioasa', code: 'DB4', type: 'city', aliases: ['PUCIOASA'] },
      { name: 'Fieni', code: 'DB5', type: 'city', aliases: ['FIENI'] },
      { name: 'Răcari', code: 'DB6', type: 'city', aliases: ['RACARI', 'RĂCARI'] },
      { name: 'Titu', code: 'DB7', type: 'city', aliases: ['TITU'] },
    ],
  },
  {
    code: 'DJ',
    name: 'Dolj',
    aliases: ['DOLJ'],
    cities: [
      { name: 'Craiova', code: 'DJ1', type: 'municipality', aliases: ['CRAIOVA', 'Mun. Craiova'] },
      { name: 'Băilești', code: 'DJ2', type: 'municipality', aliases: ['BAILESTI', 'BĂILEŞTI'] },
      { name: 'Calafat', code: 'DJ3', type: 'municipality', aliases: ['CALAFAT'] },
      { name: 'Bechet', code: 'DJ4', type: 'city', aliases: ['BECHET'] },
      { name: 'Dăbuleni', code: 'DJ5', type: 'city', aliases: ['DABULENI', 'DĂBULENI'] },
      { name: 'Filiași', code: 'DJ6', type: 'city', aliases: ['FILIASI', 'FILIAŞI'] },
      { name: 'Segarcea', code: 'DJ7', type: 'city', aliases: ['SEGARCEA'] },
    ],
  },
  {
    code: 'GL',
    name: 'Galați',
    aliases: ['GALATI', 'GALAŢI'],
    cities: [
      { name: 'Galați', code: 'GL1', type: 'municipality', aliases: ['GALATI', 'GALAŢI', 'Mun. Galați'] },
      { name: 'Tecuci', code: 'GL2', type: 'municipality', aliases: ['TECUCI'] },
      { name: 'Berești', code: 'GL3', type: 'city', aliases: ['BERESTI', 'BEREŞTI'] },
      { name: 'Târgu Bujor', code: 'GL4', type: 'city', aliases: ['TARGU BUJOR', 'TÂRGU BUJOR'] },
    ],
  },
  {
    code: 'GR',
    name: 'Giurgiu',
    aliases: ['GIURGIU'],
    cities: [
      { name: 'Giurgiu', code: 'GR1', type: 'municipality', aliases: ['GIURGIU', 'Mun. Giurgiu'] },
      { name: 'Bolintin-Vale', code: 'GR2', type: 'city', aliases: ['BOLINTIN-VALE'] },
      { name: 'Mihăilești', code: 'GR3', type: 'city', aliases: ['MIHAILESTI', 'MIHĂILEŞTI'] },
    ],
  },
  {
    code: 'GJ',
    name: 'Gorj',
    aliases: ['GORJ'],
    cities: [
      {
        name: 'Târgu Jiu',
        code: 'GJ1',
        type: 'municipality',
        aliases: ['TARGU JIU', 'TÂRGU JIU', 'Mun. Târgu Jiu', 'TG JIU'],
      },
      { name: 'Motru', code: 'GJ2', type: 'municipality', aliases: ['MOTRU'] },
      { name: 'Bumbești-Jiu', code: 'GJ3', type: 'city', aliases: ['BUMBESTI-JIU', 'BUMBEŞTI-JIU'] },
      { name: 'Novaci', code: 'GJ4', type: 'city', aliases: ['NOVACI'] },
      { name: 'Rovinari', code: 'GJ5', type: 'city', aliases: ['ROVINARI'] },
      {
        name: 'Târgu Cărbunești',
        code: 'GJ6',
        type: 'city',
        aliases: ['TARGU CARBUNESTI', 'TÂRGU CĂRBUNEŞTI', 'TG CARBUNESTI'],
      },
      { name: 'Țicleni', code: 'GJ7', type: 'city', aliases: ['TICLENI', 'ŢICLENI'] },
      { name: 'Tismana', code: 'GJ8', type: 'city', aliases: ['TISMANA'] },
    ],
  },
  {
    code: 'HR',
    name: 'Harghita',
    aliases: ['HARGHITA'],
    cities: [
      {
        name: 'Miercurea Ciuc',
        code: 'HR1',
        type: 'municipality',
        aliases: ['MIERCUREA CIUC', 'Mun. Miercurea Ciuc', 'MIERCUREA-CIUC'],
      },
      { name: 'Odorheiu Secuiesc', code: 'HR2', type: 'municipality', aliases: ['ODORHEIU SECUIESC'] },
      { name: 'Gheorgheni', code: 'HR3', type: 'municipality', aliases: ['GHEORGHENI'] },
      { name: 'Toplița', code: 'HR4', type: 'municipality', aliases: ['TOPLITA', 'TOPLIŢA'] },
      { name: 'Bălan', code: 'HR5', type: 'city', aliases: ['BALAN', 'BĂLAN'] },
      { name: 'Băile Tușnad', code: 'HR6', type: 'city', aliases: ['BAILE TUSNAD', 'BĂILE TUŞNAD'] },
      { name: 'Borsec', code: 'HR7', type: 'city', aliases: ['BORSEC'] },
      { name: 'Cristuru Secuiesc', code: 'HR8', type: 'city', aliases: ['CRISTURU SECUIESC'] },
      { name: 'Vlăhița', code: 'HR9', type: 'city', aliases: ['VLAHITA', 'VLĂHIŢA'] },
    ],
  },
  {
    code: 'HD',
    name: 'Hunedoara',
    aliases: ['HUNEDOARA'],
    cities: [
      { name: 'Deva', code: 'HD1', type: 'municipality', aliases: ['DEVA', 'Mun. Deva'] },
      { name: 'Hunedoara', code: 'HD2', type: 'municipality', aliases: ['HUNEDOARA'] },
      { name: 'Petroșani', code: 'HD3', type: 'municipality', aliases: ['PETROSANI', 'PETROŞANI'] },
      { name: 'Brad', code: 'HD4', type: 'municipality', aliases: ['BRAD'] },
      { name: 'Lupeni', code: 'HD5', type: 'municipality', aliases: ['LUPENI'] },
      { name: 'Orăștie', code: 'HD6', type: 'municipality', aliases: ['ORASTIE', 'ORĂŞTIE'] },
      { name: 'Vulcan', code: 'HD7', type: 'municipality', aliases: ['VULCAN'] },
      { name: 'Aninoasa', code: 'HD8', type: 'city', aliases: ['ANINOASA'] },
      { name: 'Călan', code: 'HD9', type: 'city', aliases: ['CALAN', 'CĂLAN'] },
      { name: 'Hațeg', code: 'HD10', type: 'city', aliases: ['HATEG', 'HAŢEG'] },
      { name: 'Petrila', code: 'HD11', type: 'city', aliases: ['PETRILA'] },
      { name: 'Simeria', code: 'HD12', type: 'city', aliases: ['SIMERIA'] },
      { name: 'Uricani', code: 'HD13', type: 'city', aliases: ['URICANI'] },
      { name: 'Geoagiu', code: 'HD14', type: 'city', aliases: ['GEOAGIU'] },
    ],
  },
  {
    code: 'IL',
    name: 'Ialomița',
    aliases: ['IALOMITA', 'IALOMIŢA'],
    cities: [
      { name: 'Slobozia', code: 'IL1', type: 'municipality', aliases: ['SLOBOZIA', 'Mun. Slobozia'] },
      { name: 'Fetești', code: 'IL2', type: 'municipality', aliases: ['FETESTI', 'FETEŞTI'] },
      { name: 'Urziceni', code: 'IL3', type: 'municipality', aliases: ['URZICENI'] },
      { name: 'Amara', code: 'IL4', type: 'city', aliases: ['AMARA'] },
      { name: 'Căzănești', code: 'IL5', type: 'city', aliases: ['CAZANESTI', 'CĂZĂNEŞTI'] },
      { name: 'Fierbinți-Târg', code: 'IL6', type: 'city', aliases: ['FIERBINTI-TARG', 'FIERBINŢI-TÂRG'] },
      { name: 'Țăndărei', code: 'IL7', type: 'city', aliases: ['TANDAREI', 'ŢĂNDĂREI'] },
    ],
  },
  {
    code: 'IS',
    name: 'Iași',
    aliases: ['IASI', 'IAŞI'],
    cities: [
      { name: 'Iași', code: 'IS1', type: 'municipality', aliases: ['IASI', 'IAŞI', 'Mun. Iași'] },
      { name: 'Pașcani', code: 'IS2', type: 'municipality', aliases: ['PASCANI', 'PAŞCANI'] },
      { name: 'Hârlău', code: 'IS3', type: 'city', aliases: ['HARLAU', 'HÂRLĂU'] },
      { name: 'Podu Iloaiei', code: 'IS4', type: 'city', aliases: ['PODU ILOAIEI'] },
      { name: 'Târgu Frumos', code: 'IS5', type: 'city', aliases: ['TARGU FRUMOS', 'TÂRGU FRUMOS', 'TG FRUMOS'] },
    ],
  },
  {
    code: 'IF',
    name: 'Ilfov',
    aliases: ['ILFOV'],
    cities: [
      { name: 'Bragadiru', code: 'IF1', type: 'city', aliases: ['BRAGADIRU'] },
      { name: 'Buftea', code: 'IF2', type: 'city', aliases: ['BUFTEA'] },
      { name: 'Chitila', code: 'IF3', type: 'city', aliases: ['CHITILA'] },
      { name: 'Măgurele', code: 'IF4', type: 'city', aliases: ['MAGURELE', 'MĂGURELE'] },
      { name: 'Otopeni', code: 'IF5', type: 'city', aliases: ['OTOPENI'] },
      { name: 'Pantelimon', code: 'IF6', type: 'city', aliases: ['PANTELIMON'] },
      { name: 'Popești-Leordeni', code: 'IF7', type: 'city', aliases: ['POPESTI-LEORDENI', 'POPEŞTI-LEORDENI'] },
      { name: 'Voluntari', code: 'IF8', type: 'city', aliases: ['VOLUNTARI'] },
    ],
  },
  {
    code: 'MM',
    name: 'Maramureș',
    aliases: ['MARAMURES', 'MARAMUREŞ'],
    cities: [
      { name: 'Baia Mare', code: 'MM1', type: 'municipality', aliases: ['BAIA MARE', 'Mun. Baia Mare'] },
      { name: 'Sighetu Marmației', code: 'MM2', type: 'municipality', aliases: ['SIGHETU MARMATIEI', 'SIGHETU MARMAŢIEI'] },
      { name: 'Borșa', code: 'MM3', type: 'city', aliases: ['BORSA', 'BORŞA'] },
      { name: 'Baia Sprie', code: 'MM4', type: 'city', aliases: ['BAIA SPRIE'] },
      { name: 'Cavnic', code: 'MM5', type: 'city', aliases: ['CAVNIC'] },
      { name: 'Dragomirești', code: 'MM6', type: 'city', aliases: ['DRAGOMIRESTI', 'DRAGOMIREŞTI'] },
      { name: 'Săliștea de Sus', code: 'MM7', type: 'city', aliases: ['SALISTEA DE SUS', 'SĂLIŞTEA DE SUS'] },
      { name: 'Seini', code: 'MM8', type: 'city', aliases: ['SEINI'] },
      { name: 'Șomcuta Mare', code: 'MM9', type: 'city', aliases: ['SOMCUTA MARE', 'ŞOMCUTA MARE'] },
      { name: 'Tăuții-Măgherăuș', code: 'MM10', type: 'city', aliases: ['TAUTII-MAGHERAUS', 'TĂUŢII-MĂGHERĂUŞ'] },
      { name: 'Târgu Lăpuș', code: 'MM11', type: 'city', aliases: ['TARGU LAPUS', 'TÂRGU LĂPUŞ', 'TG LAPUS'] },
      { name: 'Vișeu de Sus', code: 'MM12', type: 'city', aliases: ['VISEU DE SUS', 'VIŞEU DE SUS'] },
    ],
  },
  {
    code: 'MH',
    name: 'Mehedinți',
    aliases: ['MEHEDINTI', 'MEHEDINŢI'],
    cities: [
      {
        name: 'Drobeta-Turnu Severin',
        code: 'MH1',
        type: 'municipality',
        aliases: ['DROBETA-TURNU SEVERIN', 'Mun. Drobeta-Turnu Severin', 'DROBETA TURNU SEVERIN'],
      },
      { name: 'Orșova', code: 'MH2', type: 'municipality', aliases: ['ORSOVA', 'ORŞOVA'] },
      { name: 'Baia de Aramă', code: 'MH3', type: 'city', aliases: ['BAIA DE ARAMA', 'BAIA DE ARAMĂ'] },
      { name: 'Strehaia', code: 'MH4', type: 'city', aliases: ['STREHAIA'] },
      { name: 'Vânju Mare', code: 'MH5', type: 'city', aliases: ['VANJU MARE', 'VÂNJU MARE'] },
    ],
  },
  {
    code: 'MS',
    name: 'Mureș',
    aliases: ['MURES', 'MUREŞ'],
    cities: [
      {
        name: 'Târgu Mureș',
        code: 'MS1',
        type: 'municipality',
        aliases: ['TARGU MURES', 'TÂRGU MUREŞ', 'Mun. Târgu Mureș', 'TG MURES'],
      },
      { name: 'Reghin', code: 'MS2', type: 'municipality', aliases: ['REGHIN'] },
      { name: 'Sighișoara', code: 'MS3', type: 'municipality', aliases: ['SIGHISOARA', 'SIGHIŞOARA'] },
      { name: 'Târnăveni', code: 'MS4', type: 'municipality', aliases: ['TARNAVENI', 'TÂRNĂVENI'] },
      { name: 'Luduș', code: 'MS5', type: 'city', aliases: ['LUDUS', 'LUDUŞ'] },
      { name: 'Sovata', code: 'MS6', type: 'city', aliases: ['SOVATA'] },
      { name: 'Iernut', code: 'MS7', type: 'city', aliases: ['IERNUT'] },
      { name: 'Miercurea Nirajului', code: 'MS8', type: 'city', aliases: ['MIERCUREA NIRAJULUI'] },
      { name: 'Sângeorgiu de Pădure', code: 'MS9', type: 'city', aliases: ['SANGEORGIU DE PADURE', 'SÂNGEORGIU DE PĂDURE'] },
      { name: 'Sărmașu', code: 'MS10', type: 'city', aliases: ['SARMASU', 'SĂRMAŞU'] },
      { name: 'Ungheni', code: 'MS11', type: 'city', aliases: ['UNGHENI'] },
    ],
  },
  {
    code: 'NT',
    name: 'Neamț',
    aliases: ['NEAMT', 'NEAMŢ'],
    cities: [
      {
        name: 'Piatra Neamț',
        code: 'NT1',
        type: 'municipality',
        aliases: ['PIATRA NEAMT', 'PIATRA NEAMŢ', 'Mun. Piatra Neamț'],
      },
      { name: 'Roman', code: 'NT2', type: 'municipality', aliases: ['ROMAN'] },
      { name: 'Bicaz', code: 'NT3', type: 'city', aliases: ['BICAZ'] },
      { name: 'Roznov', code: 'NT4', type: 'city', aliases: ['ROZNOV'] },
      { name: 'Târgu Neamț', code: 'NT5', type: 'city', aliases: ['TARGU NEAMT', 'TÂRGU NEAMŢ', 'TG NEAMT'] },
    ],
  },
  {
    code: 'OT',
    name: 'Olt',
    aliases: ['OLT'],
    cities: [
      { name: 'Slatina', code: 'OT1', type: 'municipality', aliases: ['SLATINA', 'Mun. Slatina'] },
      { name: 'Caracal', code: 'OT2', type: 'municipality', aliases: ['CARACAL'] },
      { name: 'Balș', code: 'OT3', type: 'city', aliases: ['BALS', 'BALŞ'] },
      { name: 'Corabia', code: 'OT4', type: 'city', aliases: ['CORABIA'] },
      { name: 'Drăgănești-Olt', code: 'OT5', type: 'city', aliases: ['DRAGANESTI-OLT', 'DRĂGĂNEŞTI-OLT'] },
      { name: 'Piatra-Olt', code: 'OT6', type: 'city', aliases: ['PIATRA-OLT'] },
      { name: 'Potcoava', code: 'OT7', type: 'city', aliases: ['POTCOAVA'] },
      { name: 'Scornicești', code: 'OT8', type: 'city', aliases: ['SCORNICESTI', 'SCORNICEŞTI'] },
    ],
  },
  {
    code: 'PH',
    name: 'Prahova',
    aliases: ['PRAHOVA'],
    cities: [
      { name: 'Ploiești', code: 'PH1', type: 'municipality', aliases: ['PLOIESTI', 'PLOIEŞTI', 'Mun. Ploiești'] },
      { name: 'Câmpina', code: 'PH2', type: 'municipality', aliases: ['CAMPINA', 'CÂMPINA'] },
      { name: 'Azuga', code: 'PH3', type: 'city', aliases: ['AZUGA'] },
      { name: 'Băicoi', code: 'PH4', type: 'city', aliases: ['BAICOI', 'BĂICOI'] },
      { name: 'Breaza', code: 'PH5', type: 'city', aliases: ['BREAZA'] },
      { name: 'Bușteni', code: 'PH6', type: 'city', aliases: ['BUSTENI', 'BUŞTENI'] },
      { name: 'Comarnic', code: 'PH7', type: 'city', aliases: ['COMARNIC'] },
      { name: 'Mizil', code: 'PH8', type: 'city', aliases: ['MIZIL'] },
      { name: 'Plopeni', code: 'PH9', type: 'city', aliases: ['PLOPENI'] },
      { name: 'Sinaia', code: 'PH10', type: 'city', aliases: ['SINAIA'] },
      { name: 'Slănic', code: 'PH11', type: 'city', aliases: ['SLANIC', 'SLĂNIC'] },
      { name: 'Urlați', code: 'PH12', type: 'city', aliases: ['URLATI', 'URLAŢI'] },
      { name: 'Vălenii de Munte', code: 'PH13', type: 'city', aliases: ['VALENII DE MUNTE', 'VĂLENII DE MUNTE'] },
      { name: 'Boldești-Scăeni', code: 'PH14', type: 'city', aliases: ['BOLDESTI-SCAENI', 'BOLDEŞTI-SCĂENI'] },
    ],
  },
  {
    code: 'SM',
    name: 'Satu Mare',
    aliases: ['SATU MARE'],
    cities: [
      { name: 'Satu Mare', code: 'SM1', type: 'municipality', aliases: ['SATU MARE', 'Mun. Satu Mare'] },
      { name: 'Carei', code: 'SM2', type: 'municipality', aliases: ['CAREI'] },
      { name: 'Negrești-Oaș', code: 'SM3', type: 'city', aliases: ['NEGRESTI-OAS', 'NEGREŞTI-OAŞ'] },
      { name: 'Tășnad', code: 'SM4', type: 'city', aliases: ['TASNAD', 'TĂŞNAD'] },
      { name: 'Ardud', code: 'SM5', type: 'city', aliases: ['ARDUD'] },
      { name: 'Livada', code: 'SM6', type: 'city', aliases: ['LIVADA'] },
    ],
  },
  {
    code: 'SJ',
    name: 'Sălaj',
    aliases: ['SALAJ', 'SĂLAJ'],
    cities: [
      { name: 'Zalău', code: 'SJ1', type: 'municipality', aliases: ['ZALAU', 'ZALĂU', 'Mun. Zalău'] },
      { name: 'Cehu Silvaniei', code: 'SJ2', type: 'city', aliases: ['CEHU SILVANIEI'] },
      { name: 'Jibou', code: 'SJ3', type: 'city', aliases: ['JIBOU'] },
      { name: 'Șimleu Silvaniei', code: 'SJ4', type: 'city', aliases: ['SIMLEU SILVANIEI', 'ŞIMLEU SILVANIEI'] },
    ],
  },
  {
    code: 'SB',
    name: 'Sibiu',
    aliases: ['SIBIU'],
    cities: [
      { name: 'Sibiu', code: 'SB1', type: 'municipality', aliases: ['SIBIU', 'Mun. Sibiu'] },
      { name: 'Mediaș', code: 'SB2', type: 'municipality', aliases: ['MEDIAS', 'MEDIAŞ'] },
      { name: 'Agnita', code: 'SB3', type: 'city', aliases: ['AGNITA'] },
      { name: 'Avrig', code: 'SB4', type: 'city', aliases: ['AVRIG'] },
      { name: 'Cisnădie', code: 'SB5', type: 'city', aliases: ['CISNADIE', 'CISNĂDIE'] },
      { name: 'Copșa Mică', code: 'SB6', type: 'city', aliases: ['COPSA MICA', 'COPŞA MICĂ'] },
      { name: 'Dumbrăveni', code: 'SB7', type: 'city', aliases: ['DUMBRAVENI', 'DUMBRĂVENI'] },
      { name: 'Miercurea Sibiului', code: 'SB8', type: 'city', aliases: ['MIERCUREA SIBIULUI'] },
      { name: 'Ocna Sibiului', code: 'SB9', type: 'city', aliases: ['OCNA SIBIULUI'] },
      { name: 'Săliște', code: 'SB10', type: 'city', aliases: ['SALISTE', 'SĂLIŞTE'] },
      { name: 'Tălmaciu', code: 'SB11', type: 'city', aliases: ['TALMACIU', 'TĂLMACIU'] },
    ],
  },
  {
    code: 'SV',
    name: 'Suceava',
    aliases: ['SUCEAVA'],
    cities: [
      { name: 'Suceava', code: 'SV1', type: 'municipality', aliases: ['SUCEAVA', 'Mun. Suceava'] },
      { name: 'Fălticeni', code: 'SV2', type: 'municipality', aliases: ['FALTICENI', 'FĂLTICENI'] },
      { name: 'Rădăuți', code: 'SV3', type: 'municipality', aliases: ['RADAUTI', 'RĂDĂUŢI'] },
      {
        name: 'Câmpulung Moldovenesc',
        code: 'SV4',
        type: 'municipality',
        aliases: ['CAMPULUNG MOLDOVENESC', 'CÂMPULUNG MOLDOVENESC'],
      },
      { name: 'Vatra Dornei', code: 'SV5', type: 'municipality', aliases: ['VATRA DORNEI'] },
      { name: 'Broșteni', code: 'SV6', type: 'city', aliases: ['BROSTENI', 'BROŞTENI'] },
      { name: 'Cajvana', code: 'SV7', type: 'city', aliases: ['CAJVANA'] },
      { name: 'Dolhasca', code: 'SV8', type: 'city', aliases: ['DOLHASCA'] },
      { name: 'Frasin', code: 'SV9', type: 'city', aliases: ['FRASIN'] },
      { name: 'Gura Humorului', code: 'SV10', type: 'city', aliases: ['GURA HUMORULUI'] },
      { name: 'Liteni', code: 'SV11', type: 'city', aliases: ['LITENI'] },
      { name: 'Milișăuți', code: 'SV12', type: 'city', aliases: ['MILISAUTI', 'MILIŞĂUŢI'] },
      { name: 'Salcea', code: 'SV13', type: 'city', aliases: ['SALCEA'] },
      { name: 'Siret', code: 'SV14', type: 'city', aliases: ['SIRET'] },
      { name: 'Solca', code: 'SV15', type: 'city', aliases: ['SOLCA'] },
      { name: 'Vicovu de Sus', code: 'SV16', type: 'city', aliases: ['VICOVU DE SUS'] },
    ],
  },
  {
    code: 'TR',
    name: 'Teleorman',
    aliases: ['TELEORMAN'],
    cities: [
      { name: 'Alexandria', code: 'TR1', type: 'municipality', aliases: ['ALEXANDRIA', 'Mun. Alexandria'] },
      { name: 'Roșiori de Vede', code: 'TR2', type: 'municipality', aliases: ['ROSIORI DE VEDE', 'ROŞIORI DE VEDE'] },
      { name: 'Turnu Măgurele', code: 'TR3', type: 'municipality', aliases: ['TURNU MAGURELE', 'TURNU MĂGURELE'] },
      { name: 'Videle', code: 'TR4', type: 'city', aliases: ['VIDELE'] },
      { name: 'Zimnicea', code: 'TR5', type: 'city', aliases: ['ZIMNICEA'] },
    ],
  },
  {
    code: 'TM',
    name: 'Timiș',
    aliases: ['TIMIS', 'TIMIŞ'],
    cities: [
      { name: 'Timișoara', code: 'TM1', type: 'municipality', aliases: ['TIMISOARA', 'TIMIŞOARA', 'Mun. Timișoara'] },
      { name: 'Lugoj', code: 'TM2', type: 'municipality', aliases: ['LUGOJ'] },
      { name: 'Buziaș', code: 'TM3', type: 'city', aliases: ['BUZIAS', 'BUZIAŞ'] },
      { name: 'Ciacova', code: 'TM4', type: 'city', aliases: ['CIACOVA'] },
      { name: 'Deta', code: 'TM5', type: 'city', aliases: ['DETA'] },
      { name: 'Făget', code: 'TM6', type: 'city', aliases: ['FAGET', 'FĂGET'] },
      { name: 'Gătaia', code: 'TM7', type: 'city', aliases: ['GATAIA', 'GĂTAIA'] },
      { name: 'Jimbolia', code: 'TM8', type: 'city', aliases: ['JIMBOLIA'] },
      { name: 'Recaș', code: 'TM9', type: 'city', aliases: ['RECAS', 'RECAŞ'] },
      { name: 'Sânnicolau Mare', code: 'TM10', type: 'city', aliases: ['SANNICOLAU MARE', 'SÂNNICOLAU MARE'] },
    ],
  },
  {
    code: 'TL',
    name: 'Tulcea',
    aliases: ['TULCEA'],
    cities: [
      { name: 'Tulcea', code: 'TL1', type: 'municipality', aliases: ['TULCEA', 'Mun. Tulcea'] },
      { name: 'Babadag', code: 'TL2', type: 'city', aliases: ['BABADAG'] },
      { name: 'Isaccea', code: 'TL3', type: 'city', aliases: ['ISACCEA'] },
      { name: 'Măcin', code: 'TL4', type: 'city', aliases: ['MACIN', 'MĂCIN'] },
      { name: 'Sulina', code: 'TL5', type: 'city', aliases: ['SULINA'] },
    ],
  },
  {
    code: 'VS',
    name: 'Vaslui',
    aliases: ['VASLUI'],
    cities: [
      { name: 'Vaslui', code: 'VS1', type: 'municipality', aliases: ['VASLUI', 'Mun. Vaslui'] },
      { name: 'Bârlad', code: 'VS2', type: 'municipality', aliases: ['BARLAD', 'BÂRLAD'] },
      { name: 'Huși', code: 'VS3', type: 'municipality', aliases: ['HUSI', 'HUŞI'] },
      { name: 'Negrești', code: 'VS4', type: 'city', aliases: ['NEGRESTI', 'NEGREŞTI'] },
    ],
  },
  {
    code: 'VL',
    name: 'Vâlcea',
    aliases: ['VALCEA', 'VÂLCEA'],
    cities: [
      {
        name: 'Râmnicu Vâlcea',
        code: 'VL1',
        type: 'municipality',
        aliases: ['RAMNICU VALCEA', 'RÂMNICU VÂLCEA', 'Mun. Râmnicu Vâlcea', 'RM VALCEA'],
      },
      { name: 'Drăgășani', code: 'VL2', type: 'municipality', aliases: ['DRAGASANI', 'DRĂGĂŞANI'] },
      { name: 'Băbeni', code: 'VL3', type: 'city', aliases: ['BABENI', 'BĂBENI'] },
      { name: 'Băile Govora', code: 'VL4', type: 'city', aliases: ['BAILE GOVORA', 'BĂILE GOVORA'] },
      { name: 'Băile Olănești', code: 'VL5', type: 'city', aliases: ['BAILE OLANESTI', 'BĂILE OLĂNEŞTI'] },
      { name: 'Bălcești', code: 'VL6', type: 'city', aliases: ['BALCESTI', 'BĂLCEŞTI'] },
      { name: 'Berbești', code: 'VL7', type: 'city', aliases: ['BERBESTI', 'BERBEŞTI'] },
      { name: 'Brezoi', code: 'VL8', type: 'city', aliases: ['BREZOI'] },
      { name: 'Călimănești', code: 'VL9', type: 'city', aliases: ['CALIMANESTI', 'CĂLIMĂNEŞTI'] },
      { name: 'Horezu', code: 'VL10', type: 'city', aliases: ['HOREZU'] },
      { name: 'Ocnele Mari', code: 'VL11', type: 'city', aliases: ['OCNELE MARI'] },
    ],
  },
  {
    code: 'VN',
    name: 'Vrancea',
    aliases: ['VRANCEA'],
    cities: [
      { name: 'Focșani', code: 'VN1', type: 'municipality', aliases: ['FOCSANI', 'FOCŞANI', 'Mun. Focșani'] },
      { name: 'Adjud', code: 'VN2', type: 'municipality', aliases: ['ADJUD'] },
      { name: 'Mărășești', code: 'VN3', type: 'city', aliases: ['MARASESTI', 'MĂRĂŞEŞTI'] },
      { name: 'Odobești', code: 'VN4', type: 'city', aliases: ['ODOBESTI', 'ODOBEŞTI'] },
      { name: 'Panciu', code: 'VN5', type: 'city', aliases: ['PANCIU'] },
    ],
  },
];

async function seedLocations() {
  try {
    // Clear existing locations
    await Location.deleteMany({});
    logger.info('Cleared existing locations');

    // Insert counties and their cities
    for (const county of counties) {
      // Create county
      const countyDoc = await Location.create({
        name: county.name,
        type: 'county',
        code: county.code,
        standardizedNames: [county.name.toUpperCase(), ...county.aliases],
        aliases: county.aliases,
        isActive: true,
      });
      logger.info(`Created county: ${county.name}`);

      // Create cities for this county
      for (const city of county.cities) {
        await Location.create({
          name: city.name,
          type: city.type,
          code: city.code,
          countyCode: county.code,
          standardizedNames: [city.name.toUpperCase(), ...city.aliases],
          aliases: city.aliases,
          isActive: true,
        });
      }
      logger.info(`Created ${county.cities.length} cities for ${county.name}`);
    }

    logger.info('Location seeding completed successfully');
  } catch (error) {
    logger.error('Error seeding locations:', error);
    throw error;
  }
}

module.exports = {
  seedLocations,
  counties,
};
